// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package Message_proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Direction int32

const (
	Direction_UP    Direction = 0
	Direction_DOWN  Direction = 1
	Direction_LEFT  Direction = 2
	Direction_RIGHT Direction = 3
)

var Direction_name = map[int32]string{
	0: "UP",
	1: "DOWN",
	2: "LEFT",
	3: "RIGHT",
}

var Direction_value = map[string]int32{
	"UP":    0,
	"DOWN":  1,
	"LEFT":  2,
	"RIGHT": 3,
}

func (x Direction) String() string {
	return proto.EnumName(Direction_name, int32(x))
}

func (Direction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type Shoot_ShootType int32

const (
	Shoot_NORMAL Shoot_ShootType = 0
)

var Shoot_ShootType_name = map[int32]string{
	0: "NORMAL",
}

var Shoot_ShootType_value = map[string]int32{
	"NORMAL": 0,
}

func (x Shoot_ShootType) String() string {
	return proto.EnumName(Shoot_ShootType_name, int32(x))
}

func (Shoot_ShootType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8, 0}
}

type ClientGameMessage struct {
	InputSequenceNumber int32   `protobuf:"varint,1,opt,name=input_sequence_number,json=inputSequenceNumber,proto3" json:"input_sequence_number,omitempty"`
	TimeElapsed         float32 `protobuf:"fixed32,2,opt,name=time_elapsed,json=timeElapsed,proto3" json:"time_elapsed,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*ClientGameMessage_InitPlayerPayload
	//	*ClientGameMessage_MovePositionPayload
	//	*ClientGameMessage_ShootPayload
	//	*ClientGameMessage_BuildWallPayload
	//	*ClientGameMessage_UpdatePlayerPayload
	Message              isClientGameMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ClientGameMessage) Reset()         { *m = ClientGameMessage{} }
func (m *ClientGameMessage) String() string { return proto.CompactTextString(m) }
func (*ClientGameMessage) ProtoMessage()    {}
func (*ClientGameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *ClientGameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientGameMessage.Unmarshal(m, b)
}
func (m *ClientGameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientGameMessage.Marshal(b, m, deterministic)
}
func (m *ClientGameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientGameMessage.Merge(m, src)
}
func (m *ClientGameMessage) XXX_Size() int {
	return xxx_messageInfo_ClientGameMessage.Size(m)
}
func (m *ClientGameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientGameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ClientGameMessage proto.InternalMessageInfo

func (m *ClientGameMessage) GetInputSequenceNumber() int32 {
	if m != nil {
		return m.InputSequenceNumber
	}
	return 0
}

func (m *ClientGameMessage) GetTimeElapsed() float32 {
	if m != nil {
		return m.TimeElapsed
	}
	return 0
}

type isClientGameMessage_Message interface {
	isClientGameMessage_Message()
}

type ClientGameMessage_InitPlayerPayload struct {
	InitPlayerPayload *InitPlayer `protobuf:"bytes,3,opt,name=init_player_payload,json=initPlayerPayload,proto3,oneof"`
}

type ClientGameMessage_MovePositionPayload struct {
	MovePositionPayload *MovePosition `protobuf:"bytes,4,opt,name=move_position_payload,json=movePositionPayload,proto3,oneof"`
}

type ClientGameMessage_ShootPayload struct {
	ShootPayload *Shoot `protobuf:"bytes,5,opt,name=shoot_payload,json=shootPayload,proto3,oneof"`
}

type ClientGameMessage_BuildWallPayload struct {
	BuildWallPayload *BuildWall `protobuf:"bytes,6,opt,name=build_wall_payload,json=buildWallPayload,proto3,oneof"`
}

type ClientGameMessage_UpdatePlayerPayload struct {
	UpdatePlayerPayload *UpdatePlayer `protobuf:"bytes,7,opt,name=update_player_payload,json=updatePlayerPayload,proto3,oneof"`
}

func (*ClientGameMessage_InitPlayerPayload) isClientGameMessage_Message() {}

func (*ClientGameMessage_MovePositionPayload) isClientGameMessage_Message() {}

func (*ClientGameMessage_ShootPayload) isClientGameMessage_Message() {}

func (*ClientGameMessage_BuildWallPayload) isClientGameMessage_Message() {}

func (*ClientGameMessage_UpdatePlayerPayload) isClientGameMessage_Message() {}

func (m *ClientGameMessage) GetMessage() isClientGameMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ClientGameMessage) GetInitPlayerPayload() *InitPlayer {
	if x, ok := m.GetMessage().(*ClientGameMessage_InitPlayerPayload); ok {
		return x.InitPlayerPayload
	}
	return nil
}

func (m *ClientGameMessage) GetMovePositionPayload() *MovePosition {
	if x, ok := m.GetMessage().(*ClientGameMessage_MovePositionPayload); ok {
		return x.MovePositionPayload
	}
	return nil
}

func (m *ClientGameMessage) GetShootPayload() *Shoot {
	if x, ok := m.GetMessage().(*ClientGameMessage_ShootPayload); ok {
		return x.ShootPayload
	}
	return nil
}

func (m *ClientGameMessage) GetBuildWallPayload() *BuildWall {
	if x, ok := m.GetMessage().(*ClientGameMessage_BuildWallPayload); ok {
		return x.BuildWallPayload
	}
	return nil
}

func (m *ClientGameMessage) GetUpdatePlayerPayload() *UpdatePlayer {
	if x, ok := m.GetMessage().(*ClientGameMessage_UpdatePlayerPayload); ok {
		return x.UpdatePlayerPayload
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ClientGameMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ClientGameMessage_InitPlayerPayload)(nil),
		(*ClientGameMessage_MovePositionPayload)(nil),
		(*ClientGameMessage_ShootPayload)(nil),
		(*ClientGameMessage_BuildWallPayload)(nil),
		(*ClientGameMessage_UpdatePlayerPayload)(nil),
	}
}

type Ping struct {
	Ping                 string   `protobuf:"bytes,1,opt,name=ping,proto3" json:"ping,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

func (m *Ping) GetPing() string {
	if m != nil {
		return m.Ping
	}
	return ""
}

type MovePosition struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Dx                   float32  `protobuf:"fixed32,2,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy                   float32  `protobuf:"fixed32,3,opt,name=dy,proto3" json:"dy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovePosition) Reset()         { *m = MovePosition{} }
func (m *MovePosition) String() string { return proto.CompactTextString(m) }
func (*MovePosition) ProtoMessage()    {}
func (*MovePosition) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MovePosition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovePosition.Unmarshal(m, b)
}
func (m *MovePosition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovePosition.Marshal(b, m, deterministic)
}
func (m *MovePosition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovePosition.Merge(m, src)
}
func (m *MovePosition) XXX_Size() int {
	return xxx_messageInfo_MovePosition.Size(m)
}
func (m *MovePosition) XXX_DiscardUnknown() {
	xxx_messageInfo_MovePosition.DiscardUnknown(m)
}

var xxx_messageInfo_MovePosition proto.InternalMessageInfo

func (m *MovePosition) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MovePosition) GetDx() float32 {
	if m != nil {
		return m.Dx
	}
	return 0
}

func (m *MovePosition) GetDy() float32 {
	if m != nil {
		return m.Dy
	}
	return 0
}

type InitPlayer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId             int32    `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	X                    float32  `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	IsMain               bool     `protobuf:"varint,6,opt,name=is_main,json=isMain,proto3" json:"is_main,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitPlayer) Reset()         { *m = InitPlayer{} }
func (m *InitPlayer) String() string { return proto.CompactTextString(m) }
func (*InitPlayer) ProtoMessage()    {}
func (*InitPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *InitPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitPlayer.Unmarshal(m, b)
}
func (m *InitPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitPlayer.Marshal(b, m, deterministic)
}
func (m *InitPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitPlayer.Merge(m, src)
}
func (m *InitPlayer) XXX_Size() int {
	return xxx_messageInfo_InitPlayer.Size(m)
}
func (m *InitPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_InitPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_InitPlayer proto.InternalMessageInfo

func (m *InitPlayer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *InitPlayer) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *InitPlayer) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *InitPlayer) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *InitPlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InitPlayer) GetIsMain() bool {
	if m != nil {
		return m.IsMain
	}
	return false
}

type Map struct {
	Block                []int32  `protobuf:"varint,1,rep,packed,name=block,proto3" json:"block,omitempty"`
	NumCols              int32    `protobuf:"varint,2,opt,name=num_cols,json=numCols,proto3" json:"num_cols,omitempty"`
	NumRows              int32    `protobuf:"varint,3,opt,name=num_rows,json=numRows,proto3" json:"num_rows,omitempty"`
	BlockWidth           float32  `protobuf:"fixed32,4,opt,name=block_width,json=blockWidth,proto3" json:"block_width,omitempty"`
	BlockHeight          float32  `protobuf:"fixed32,5,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Map) Reset()         { *m = Map{} }
func (m *Map) String() string { return proto.CompactTextString(m) }
func (*Map) ProtoMessage()    {}
func (*Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map.Unmarshal(m, b)
}
func (m *Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map.Marshal(b, m, deterministic)
}
func (m *Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map.Merge(m, src)
}
func (m *Map) XXX_Size() int {
	return xxx_messageInfo_Map.Size(m)
}
func (m *Map) XXX_DiscardUnknown() {
	xxx_messageInfo_Map.DiscardUnknown(m)
}

var xxx_messageInfo_Map proto.InternalMessageInfo

func (m *Map) GetBlock() []int32 {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Map) GetNumCols() int32 {
	if m != nil {
		return m.NumCols
	}
	return 0
}

func (m *Map) GetNumRows() int32 {
	if m != nil {
		return m.NumRows
	}
	return 0
}

func (m *Map) GetBlockWidth() float32 {
	if m != nil {
		return m.BlockWidth
	}
	return 0
}

func (m *Map) GetBlockHeight() float32 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type InitAll struct {
	InitPlayer           []*InitPlayer `protobuf:"bytes,1,rep,name=init_player,json=initPlayer,proto3" json:"init_player,omitempty"`
	InitMap              *Map          `protobuf:"bytes,2,opt,name=init_map,json=initMap,proto3" json:"init_map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InitAll) Reset()         { *m = InitAll{} }
func (m *InitAll) String() string { return proto.CompactTextString(m) }
func (*InitAll) ProtoMessage()    {}
func (*InitAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *InitAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitAll.Unmarshal(m, b)
}
func (m *InitAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitAll.Marshal(b, m, deterministic)
}
func (m *InitAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitAll.Merge(m, src)
}
func (m *InitAll) XXX_Size() int {
	return xxx_messageInfo_InitAll.Size(m)
}
func (m *InitAll) XXX_DiscardUnknown() {
	xxx_messageInfo_InitAll.DiscardUnknown(m)
}

var xxx_messageInfo_InitAll proto.InternalMessageInfo

func (m *InitAll) GetInitPlayer() []*InitPlayer {
	if m != nil {
		return m.InitPlayer
	}
	return nil
}

func (m *InitAll) GetInitMap() *Map {
	if m != nil {
		return m.InitMap
	}
	return nil
}

type RemovePlayer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemovePlayer) Reset()         { *m = RemovePlayer{} }
func (m *RemovePlayer) String() string { return proto.CompactTextString(m) }
func (*RemovePlayer) ProtoMessage()    {}
func (*RemovePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *RemovePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemovePlayer.Unmarshal(m, b)
}
func (m *RemovePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemovePlayer.Marshal(b, m, deterministic)
}
func (m *RemovePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemovePlayer.Merge(m, src)
}
func (m *RemovePlayer) XXX_Size() int {
	return xxx_messageInfo_RemovePlayer.Size(m)
}
func (m *RemovePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_RemovePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_RemovePlayer proto.InternalMessageInfo

func (m *RemovePlayer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type RegisterClientID struct {
	ClientId             int32    `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterClientID) Reset()         { *m = RegisterClientID{} }
func (m *RegisterClientID) String() string { return proto.CompactTextString(m) }
func (*RegisterClientID) ProtoMessage()    {}
func (*RegisterClientID) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *RegisterClientID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterClientID.Unmarshal(m, b)
}
func (m *RegisterClientID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterClientID.Marshal(b, m, deterministic)
}
func (m *RegisterClientID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterClientID.Merge(m, src)
}
func (m *RegisterClientID) XXX_Size() int {
	return xxx_messageInfo_RegisterClientID.Size(m)
}
func (m *RegisterClientID) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterClientID.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterClientID proto.InternalMessageInfo

func (m *RegisterClientID) GetClientId() int32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

type Shoot struct {
	Id                   int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PlayerId             int32           `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                    float32         `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32         `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	Dx                   float32         `protobuf:"fixed32,5,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy                   float32         `protobuf:"fixed32,6,opt,name=dy,proto3" json:"dy,omitempty"`
	Type                 Shoot_ShootType `protobuf:"varint,7,opt,name=type,proto3,enum=Message_proto.Shoot_ShootType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Shoot) Reset()         { *m = Shoot{} }
func (m *Shoot) String() string { return proto.CompactTextString(m) }
func (*Shoot) ProtoMessage()    {}
func (*Shoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{8}
}

func (m *Shoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Shoot.Unmarshal(m, b)
}
func (m *Shoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Shoot.Marshal(b, m, deterministic)
}
func (m *Shoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Shoot.Merge(m, src)
}
func (m *Shoot) XXX_Size() int {
	return xxx_messageInfo_Shoot.Size(m)
}
func (m *Shoot) XXX_DiscardUnknown() {
	xxx_messageInfo_Shoot.DiscardUnknown(m)
}

var xxx_messageInfo_Shoot proto.InternalMessageInfo

func (m *Shoot) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Shoot) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Shoot) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Shoot) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Shoot) GetDx() float32 {
	if m != nil {
		return m.Dx
	}
	return 0
}

func (m *Shoot) GetDy() float32 {
	if m != nil {
		return m.Dy
	}
	return 0
}

func (m *Shoot) GetType() Shoot_ShootType {
	if m != nil {
		return m.Type
	}
	return Shoot_NORMAL
}

type BuildWall struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    int32    `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildWall) Reset()         { *m = BuildWall{} }
func (m *BuildWall) String() string { return proto.CompactTextString(m) }
func (*BuildWall) ProtoMessage()    {}
func (*BuildWall) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{9}
}

func (m *BuildWall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildWall.Unmarshal(m, b)
}
func (m *BuildWall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildWall.Marshal(b, m, deterministic)
}
func (m *BuildWall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildWall.Merge(m, src)
}
func (m *BuildWall) XXX_Size() int {
	return xxx_messageInfo_BuildWall.Size(m)
}
func (m *BuildWall) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildWall.DiscardUnknown(m)
}

var xxx_messageInfo_BuildWall proto.InternalMessageInfo

func (m *BuildWall) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BuildWall) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BuildWall) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type UpdatePlayer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    float32  `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Health               float32  `protobuf:"fixed32,4,opt,name=health,proto3" json:"health,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	IsDestroy            bool     `protobuf:"varint,6,opt,name=is_destroy,json=isDestroy,proto3" json:"is_destroy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlayer) Reset()         { *m = UpdatePlayer{} }
func (m *UpdatePlayer) String() string { return proto.CompactTextString(m) }
func (*UpdatePlayer) ProtoMessage()    {}
func (*UpdatePlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{10}
}

func (m *UpdatePlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlayer.Unmarshal(m, b)
}
func (m *UpdatePlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlayer.Marshal(b, m, deterministic)
}
func (m *UpdatePlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlayer.Merge(m, src)
}
func (m *UpdatePlayer) XXX_Size() int {
	return xxx_messageInfo_UpdatePlayer.Size(m)
}
func (m *UpdatePlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlayer.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlayer proto.InternalMessageInfo

func (m *UpdatePlayer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePlayer) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *UpdatePlayer) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *UpdatePlayer) GetHealth() float32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *UpdatePlayer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdatePlayer) GetIsDestroy() bool {
	if m != nil {
		return m.IsDestroy
	}
	return false
}

type Player struct {
	Id                   int32                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	X                    float32              `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32              `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Health               float32              `protobuf:"fixed32,4,opt,name=health,proto3" json:"health,omitempty"`
	Size                 float32              `protobuf:"fixed32,5,opt,name=size,proto3" json:"size,omitempty"`
	Level                int32                `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	Score                int32                `protobuf:"varint,7,opt,name=score,proto3" json:"score,omitempty"`
	Name                 string               `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	NextReload           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=next_reload,json=nextReload,proto3" json:"next_reload,omitempty"`
	IsDestroy            bool                 `protobuf:"varint,10,opt,name=is_destroy,json=isDestroy,proto3" json:"is_destroy,omitempty"`
	CurrentInputNumber   int32                `protobuf:"varint,11,opt,name=current_input_number,json=currentInputNumber,proto3" json:"current_input_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{11}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Player) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Player) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Player) GetHealth() float32 {
	if m != nil {
		return m.Health
	}
	return 0
}

func (m *Player) GetSize() float32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Player) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Player) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetNextReload() *timestamp.Timestamp {
	if m != nil {
		return m.NextReload
	}
	return nil
}

func (m *Player) GetIsDestroy() bool {
	if m != nil {
		return m.IsDestroy
	}
	return false
}

func (m *Player) GetCurrentInputNumber() int32 {
	if m != nil {
		return m.CurrentInputNumber
	}
	return 0
}

type ServerGameMessage struct {
	LastProcessInput int32 `protobuf:"varint,1,opt,name=last_process_input,json=lastProcessInput,proto3" json:"last_process_input,omitempty"`
	// Types that are valid to be assigned to Message:
	//	*ServerGameMessage_InitAllPayload
	//	*ServerGameMessage_InitPlayerPayload
	//	*ServerGameMessage_UpdatePlayerPayload
	//	*ServerGameMessage_InitShootPayload
	//	*ServerGameMessage_RemovePlayerPayload
	//	*ServerGameMessage_RegisterClientIdPayload
	Message              isServerGameMessage_Message `protobuf_oneof:"message"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ServerGameMessage) Reset()         { *m = ServerGameMessage{} }
func (m *ServerGameMessage) String() string { return proto.CompactTextString(m) }
func (*ServerGameMessage) ProtoMessage()    {}
func (*ServerGameMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{12}
}

func (m *ServerGameMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerGameMessage.Unmarshal(m, b)
}
func (m *ServerGameMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerGameMessage.Marshal(b, m, deterministic)
}
func (m *ServerGameMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerGameMessage.Merge(m, src)
}
func (m *ServerGameMessage) XXX_Size() int {
	return xxx_messageInfo_ServerGameMessage.Size(m)
}
func (m *ServerGameMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerGameMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ServerGameMessage proto.InternalMessageInfo

func (m *ServerGameMessage) GetLastProcessInput() int32 {
	if m != nil {
		return m.LastProcessInput
	}
	return 0
}

type isServerGameMessage_Message interface {
	isServerGameMessage_Message()
}

type ServerGameMessage_InitAllPayload struct {
	InitAllPayload *InitAll `protobuf:"bytes,2,opt,name=init_all_payload,json=initAllPayload,proto3,oneof"`
}

type ServerGameMessage_InitPlayerPayload struct {
	InitPlayerPayload *InitPlayer `protobuf:"bytes,3,opt,name=init_player_payload,json=initPlayerPayload,proto3,oneof"`
}

type ServerGameMessage_UpdatePlayerPayload struct {
	UpdatePlayerPayload *Player `protobuf:"bytes,4,opt,name=update_player_payload,json=updatePlayerPayload,proto3,oneof"`
}

type ServerGameMessage_InitShootPayload struct {
	InitShootPayload *Shoot `protobuf:"bytes,5,opt,name=init_shoot_payload,json=initShootPayload,proto3,oneof"`
}

type ServerGameMessage_RemovePlayerPayload struct {
	RemovePlayerPayload *RemovePlayer `protobuf:"bytes,6,opt,name=remove_player_payload,json=removePlayerPayload,proto3,oneof"`
}

type ServerGameMessage_RegisterClientIdPayload struct {
	RegisterClientIdPayload *RegisterClientID `protobuf:"bytes,7,opt,name=register_client_id_payload,json=registerClientIdPayload,proto3,oneof"`
}

func (*ServerGameMessage_InitAllPayload) isServerGameMessage_Message() {}

func (*ServerGameMessage_InitPlayerPayload) isServerGameMessage_Message() {}

func (*ServerGameMessage_UpdatePlayerPayload) isServerGameMessage_Message() {}

func (*ServerGameMessage_InitShootPayload) isServerGameMessage_Message() {}

func (*ServerGameMessage_RemovePlayerPayload) isServerGameMessage_Message() {}

func (*ServerGameMessage_RegisterClientIdPayload) isServerGameMessage_Message() {}

func (m *ServerGameMessage) GetMessage() isServerGameMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ServerGameMessage) GetInitAllPayload() *InitAll {
	if x, ok := m.GetMessage().(*ServerGameMessage_InitAllPayload); ok {
		return x.InitAllPayload
	}
	return nil
}

func (m *ServerGameMessage) GetInitPlayerPayload() *InitPlayer {
	if x, ok := m.GetMessage().(*ServerGameMessage_InitPlayerPayload); ok {
		return x.InitPlayerPayload
	}
	return nil
}

func (m *ServerGameMessage) GetUpdatePlayerPayload() *Player {
	if x, ok := m.GetMessage().(*ServerGameMessage_UpdatePlayerPayload); ok {
		return x.UpdatePlayerPayload
	}
	return nil
}

func (m *ServerGameMessage) GetInitShootPayload() *Shoot {
	if x, ok := m.GetMessage().(*ServerGameMessage_InitShootPayload); ok {
		return x.InitShootPayload
	}
	return nil
}

func (m *ServerGameMessage) GetRemovePlayerPayload() *RemovePlayer {
	if x, ok := m.GetMessage().(*ServerGameMessage_RemovePlayerPayload); ok {
		return x.RemovePlayerPayload
	}
	return nil
}

func (m *ServerGameMessage) GetRegisterClientIdPayload() *RegisterClientID {
	if x, ok := m.GetMessage().(*ServerGameMessage_RegisterClientIdPayload); ok {
		return x.RegisterClientIdPayload
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ServerGameMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ServerGameMessage_InitAllPayload)(nil),
		(*ServerGameMessage_InitPlayerPayload)(nil),
		(*ServerGameMessage_UpdatePlayerPayload)(nil),
		(*ServerGameMessage_InitShootPayload)(nil),
		(*ServerGameMessage_RemovePlayerPayload)(nil),
		(*ServerGameMessage_RegisterClientIdPayload)(nil),
	}
}

type WallBlock struct {
	X                    float32  `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WallBlock) Reset()         { *m = WallBlock{} }
func (m *WallBlock) String() string { return proto.CompactTextString(m) }
func (*WallBlock) ProtoMessage()    {}
func (*WallBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{13}
}

func (m *WallBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WallBlock.Unmarshal(m, b)
}
func (m *WallBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WallBlock.Marshal(b, m, deterministic)
}
func (m *WallBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WallBlock.Merge(m, src)
}
func (m *WallBlock) XXX_Size() int {
	return xxx_messageInfo_WallBlock.Size(m)
}
func (m *WallBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_WallBlock.DiscardUnknown(m)
}

var xxx_messageInfo_WallBlock proto.InternalMessageInfo

func (m *WallBlock) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *WallBlock) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Bullet struct {
	PlayerId             int32    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Sx                   float32  `protobuf:"fixed32,2,opt,name=sx,proto3" json:"sx,omitempty"`
	Sy                   float32  `protobuf:"fixed32,3,opt,name=sy,proto3" json:"sy,omitempty"`
	X                    float32  `protobuf:"fixed32,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float32  `protobuf:"fixed32,5,opt,name=y,proto3" json:"y,omitempty"`
	Dx                   float32  `protobuf:"fixed32,6,opt,name=dx,proto3" json:"dx,omitempty"`
	Dy                   float32  `protobuf:"fixed32,7,opt,name=dy,proto3" json:"dy,omitempty"`
	Stime                float32  `protobuf:"fixed32,8,opt,name=stime,proto3" json:"stime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bullet) Reset()         { *m = Bullet{} }
func (m *Bullet) String() string { return proto.CompactTextString(m) }
func (*Bullet) ProtoMessage()    {}
func (*Bullet) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{14}
}

func (m *Bullet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bullet.Unmarshal(m, b)
}
func (m *Bullet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bullet.Marshal(b, m, deterministic)
}
func (m *Bullet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bullet.Merge(m, src)
}
func (m *Bullet) XXX_Size() int {
	return xxx_messageInfo_Bullet.Size(m)
}
func (m *Bullet) XXX_DiscardUnknown() {
	xxx_messageInfo_Bullet.DiscardUnknown(m)
}

var xxx_messageInfo_Bullet proto.InternalMessageInfo

func (m *Bullet) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *Bullet) GetSx() float32 {
	if m != nil {
		return m.Sx
	}
	return 0
}

func (m *Bullet) GetSy() float32 {
	if m != nil {
		return m.Sy
	}
	return 0
}

func (m *Bullet) GetX() float32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Bullet) GetY() float32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Bullet) GetDx() float32 {
	if m != nil {
		return m.Dx
	}
	return 0
}

func (m *Bullet) GetDy() float32 {
	if m != nil {
		return m.Dy
	}
	return 0
}

func (m *Bullet) GetStime() float32 {
	if m != nil {
		return m.Stime
	}
	return 0
}

func init() {
	proto.RegisterEnum("Message_proto.Direction", Direction_name, Direction_value)
	proto.RegisterEnum("Message_proto.Shoot_ShootType", Shoot_ShootType_name, Shoot_ShootType_value)
	proto.RegisterType((*ClientGameMessage)(nil), "Message_proto.ClientGameMessage")
	proto.RegisterType((*Ping)(nil), "Message_proto.Ping")
	proto.RegisterType((*MovePosition)(nil), "Message_proto.MovePosition")
	proto.RegisterType((*InitPlayer)(nil), "Message_proto.InitPlayer")
	proto.RegisterType((*Map)(nil), "Message_proto.Map")
	proto.RegisterType((*InitAll)(nil), "Message_proto.InitAll")
	proto.RegisterType((*RemovePlayer)(nil), "Message_proto.RemovePlayer")
	proto.RegisterType((*RegisterClientID)(nil), "Message_proto.RegisterClientID")
	proto.RegisterType((*Shoot)(nil), "Message_proto.Shoot")
	proto.RegisterType((*BuildWall)(nil), "Message_proto.BuildWall")
	proto.RegisterType((*UpdatePlayer)(nil), "Message_proto.UpdatePlayer")
	proto.RegisterType((*Player)(nil), "Message_proto.Player")
	proto.RegisterType((*ServerGameMessage)(nil), "Message_proto.ServerGameMessage")
	proto.RegisterType((*WallBlock)(nil), "Message_proto.WallBlock")
	proto.RegisterType((*Bullet)(nil), "Message_proto.Bullet")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0xa9, 0x5f, 0x8e, 0x64, 0x43, 0x5e, 0xdb, 0xb1, 0xe3, 0xa0, 0xb1, 0xcb, 0x4b, 0x8d,
	0xa2, 0x95, 0x0b, 0xf5, 0x50, 0xa0, 0x01, 0x0a, 0xd8, 0x71, 0x1a, 0x19, 0x89, 0x1c, 0x65, 0xed,
	0xc0, 0xb7, 0x12, 0x94, 0xb8, 0x95, 0x17, 0xe5, 0x5f, 0xb9, 0xa4, 0x6d, 0xf6, 0x58, 0xa0, 0x8f,
	0x50, 0xf4, 0x01, 0x7a, 0xef, 0x1b, 0xf4, 0x99, 0xfa, 0x0a, 0xc5, 0xce, 0x92, 0x34, 0x49, 0x2b,
	0x29, 0x0a, 0xe4, 0x22, 0xec, 0xcc, 0xce, 0x7e, 0x9c, 0xdd, 0xf9, 0x66, 0x3e, 0xc1, 0x9a, 0xc7,
	0x84, 0xb0, 0x97, 0x6c, 0x14, 0x46, 0x41, 0x1c, 0x90, 0xb5, 0xa9, 0x32, 0x2d, 0x34, 0xf7, 0xf6,
	0x97, 0x41, 0xb0, 0x74, 0xd9, 0x11, 0x5a, 0xf3, 0xe4, 0xc7, 0xa3, 0x98, 0x7b, 0x4c, 0xc4, 0xb6,
	0x17, 0xaa, 0x78, 0xf3, 0x9f, 0x26, 0x6c, 0x3c, 0x77, 0x39, 0xf3, 0xe3, 0x97, 0xb6, 0xc7, 0xb2,
	0xc3, 0x64, 0x0c, 0xdb, 0xdc, 0x0f, 0x93, 0xd8, 0x12, 0xec, 0xe7, 0x84, 0xf9, 0x0b, 0x66, 0xf9,
	0x89, 0x37, 0x67, 0xd1, 0xae, 0x76, 0xa0, 0x1d, 0xb6, 0xe9, 0x26, 0x6e, 0x5e, 0x64, 0x7b, 0xe7,
	0xb8, 0x45, 0x3e, 0x85, 0x81, 0x04, 0xb7, 0x98, 0x6b, 0x87, 0x82, 0x39, 0xbb, 0xfa, 0x81, 0x76,
	0xa8, 0xd3, 0xbe, 0xf4, 0xbd, 0x50, 0x2e, 0xf2, 0x0a, 0x36, 0xb9, 0xcf, 0x63, 0x2b, 0x74, 0xed,
	0x94, 0x45, 0x56, 0x68, 0xa7, 0x6e, 0x60, 0x3b, 0xbb, 0xcd, 0x03, 0xed, 0xb0, 0x3f, 0x7e, 0x3c,
	0xaa, 0xa4, 0x3e, 0x3a, 0xf3, 0x79, 0x3c, 0xc3, 0xc0, 0x49, 0x83, 0x6e, 0xf0, 0xc2, 0x9a, 0xa9,
	0x53, 0xe4, 0x2d, 0x6c, 0x7b, 0xc1, 0x0d, 0xb3, 0xc2, 0x40, 0xf0, 0x98, 0x07, 0x7e, 0x01, 0xd7,
	0x42, 0xb8, 0x27, 0x35, 0xb8, 0x69, 0x70, 0xc3, 0x66, 0x59, 0xe8, 0xa4, 0x41, 0x37, 0xbd, 0x92,
	0x9d, 0x43, 0x3e, 0x83, 0x35, 0x71, 0x1d, 0x04, 0x71, 0x01, 0xd5, 0x46, 0xa8, 0xad, 0x1a, 0xd4,
	0x85, 0x8c, 0x99, 0x34, 0xe8, 0x00, 0x83, 0xf3, 0xc3, 0x13, 0x20, 0xf3, 0x84, 0xbb, 0x8e, 0x75,
	0x6b, 0xbb, 0x6e, 0x81, 0xd0, 0x41, 0x84, 0xdd, 0x1a, 0xc2, 0x89, 0x0c, 0xbc, 0xb2, 0x5d, 0x77,
	0xd2, 0xa0, 0xc3, 0x79, 0x6e, 0x94, 0x6e, 0x96, 0x84, 0x8e, 0x1d, 0xb3, 0xfa, 0x43, 0x75, 0x57,
	0xde, 0xec, 0x1d, 0xc6, 0x16, 0x4f, 0xb5, 0x99, 0x94, 0xec, 0x0c, 0xf2, 0xc4, 0x80, 0x6e, 0xc6,
	0x13, 0x73, 0x0f, 0x5a, 0x33, 0xee, 0x2f, 0x09, 0x81, 0x56, 0xc8, 0xfd, 0x25, 0x96, 0xd4, 0xa0,
	0xb8, 0x36, 0xbf, 0x83, 0x41, 0xf9, 0x9d, 0xc8, 0x3a, 0xe8, 0xdc, 0xc9, 0x8a, 0xae, 0x73, 0x47,
	0xda, 0xce, 0x5d, 0x56, 0x59, 0xdd, 0xb9, 0x43, 0x3b, 0xc5, 0xfa, 0x49, 0x3b, 0x35, 0x7f, 0xd5,
	0x00, 0xee, 0xeb, 0xf6, 0xe0, 0xf8, 0x13, 0x30, 0x16, 0xc8, 0x35, 0x8b, 0x2b, 0x7e, 0xb4, 0x69,
	0x4f, 0x39, 0xce, 0x1c, 0x32, 0x00, 0xed, 0x2e, 0x83, 0xd2, 0xee, 0xa4, 0x95, 0x62, 0x25, 0x75,
	0xaa, 0xa5, 0x32, 0x57, 0xdf, 0xf6, 0x18, 0xd6, 0xc3, 0xa0, 0xb8, 0x26, 0x3b, 0xd0, 0xe5, 0xc2,
	0xf2, 0x6c, 0xee, 0xe3, 0x23, 0xf7, 0x68, 0x87, 0x8b, 0xa9, 0xcd, 0x7d, 0xf3, 0x77, 0x0d, 0x9a,
	0x53, 0x3b, 0x24, 0x5b, 0xd0, 0x9e, 0xbb, 0xc1, 0xe2, 0xa7, 0x5d, 0xed, 0xa0, 0x79, 0xd8, 0xa6,
	0xca, 0x20, 0x8f, 0xa1, 0xe7, 0x27, 0x9e, 0xb5, 0x08, 0x5c, 0x91, 0xa5, 0xd0, 0xf5, 0x13, 0xef,
	0x79, 0xe0, 0x8a, 0x7c, 0x2b, 0x0a, 0x6e, 0x05, 0x26, 0xa2, 0xb6, 0x68, 0x70, 0x2b, 0xc8, 0x3e,
	0xf4, 0xf1, 0xb8, 0x75, 0xcb, 0x9d, 0xf8, 0x3a, 0x4b, 0x0c, 0xd0, 0x75, 0x25, 0x3d, 0x92, 0xfd,
	0x2a, 0xe0, 0x9a, 0xf1, 0xe5, 0x75, 0x8c, 0x99, 0xea, 0x54, 0x1d, 0x9a, 0xa0, 0xcb, 0x8c, 0xa1,
	0x2b, 0xdf, 0xe6, 0xd8, 0x75, 0xc9, 0xb7, 0xd0, 0x2f, 0x35, 0x02, 0x26, 0xf8, 0xa1, 0x06, 0xa0,
	0x70, 0x4f, 0x7f, 0xf2, 0x25, 0xf4, 0xf0, 0xac, 0x67, 0x87, 0x78, 0x81, 0xfe, 0x98, 0xd4, 0xa9,
	0x6e, 0x87, 0xb4, 0x2b, 0x63, 0xa6, 0x76, 0x68, 0x3e, 0x85, 0x01, 0x65, 0x48, 0xf6, 0x95, 0x35,
	0x31, 0x8f, 0x60, 0x48, 0xd9, 0x92, 0x8b, 0x98, 0x45, 0x6a, 0x0e, 0x9c, 0x9d, 0x56, 0xeb, 0xa4,
	0x55, 0xeb, 0x64, 0xfe, 0xad, 0x41, 0x1b, 0x3b, 0xa0, 0x04, 0xd5, 0xcc, 0xcb, 0x9b, 0x11, 0xf6,
	0xbe, 0xbc, 0xca, 0xf1, 0x1f, 0xe5, 0x55, 0xb4, 0x6a, 0xd7, 0x68, 0xd5, 0xc9, 0x69, 0x45, 0xc6,
	0xd0, 0x8a, 0xd3, 0x90, 0x21, 0xff, 0xd7, 0xc7, 0x4f, 0x57, 0xb5, 0xa3, 0xfa, 0xbd, 0x4c, 0x43,
	0x46, 0x31, 0xd6, 0xdc, 0x01, 0xa3, 0x70, 0x11, 0x80, 0xce, 0xf9, 0x1b, 0x3a, 0x3d, 0x7e, 0x3d,
	0x6c, 0x98, 0xdf, 0x80, 0x51, 0xb4, 0xdf, 0x03, 0x86, 0x62, 0x96, 0x2a, 0xf5, 0x3c, 0x4b, 0xc5,
	0x04, 0x2d, 0x35, 0x7f, 0xd3, 0x60, 0x50, 0xee, 0xb5, 0xf7, 0x1f, 0xd6, 0x2b, 0x87, 0xf1, 0x8a,
	0x8f, 0xa0, 0x73, 0xcd, 0x6c, 0xb7, 0xe0, 0x4e, 0x66, 0xad, 0x64, 0xf6, 0x27, 0x00, 0x5c, 0x58,
	0x0e, 0x13, 0x71, 0x14, 0xa4, 0x19, 0xb9, 0x0d, 0x2e, 0x4e, 0x95, 0xc3, 0xfc, 0x4b, 0x87, 0xce,
	0xc7, 0xcd, 0x40, 0xf0, 0x5f, 0x58, 0xf6, 0xfc, 0xb8, 0x96, 0xad, 0xe3, 0xb2, 0x1b, 0xe6, 0xe2,
	0xc7, 0xdb, 0x54, 0x19, 0xd2, 0x2b, 0x16, 0x41, 0xa4, 0xea, 0xd0, 0xa6, 0xca, 0x28, 0x6e, 0xd0,
	0x2b, 0xdd, 0xe0, 0x19, 0xf4, 0x7d, 0x76, 0x17, 0x5b, 0x11, 0xc3, 0xb9, 0x65, 0x20, 0x4d, 0xf7,
	0x46, 0x4a, 0x8c, 0x46, 0xb9, 0x18, 0x8d, 0x2e, 0x73, 0x31, 0xa2, 0x20, 0xc3, 0x29, 0x46, 0xd7,
	0xae, 0x0f, 0xb5, 0xeb, 0x93, 0xaf, 0x60, 0x6b, 0x91, 0x44, 0x11, 0xb2, 0x13, 0x35, 0x2a, 0x93,
	0xa6, 0x3e, 0x26, 0x45, 0xb2, 0xbd, 0x33, 0xb9, 0xa5, 0x94, 0xc9, 0xfc, 0xb3, 0x05, 0x1b, 0x17,
	0x2c, 0xba, 0x61, 0x51, 0x59, 0xe3, 0xbe, 0x00, 0xe2, 0xda, 0x22, 0x96, 0x24, 0x5a, 0x30, 0x21,
	0x14, 0x58, 0xf6, 0x96, 0x43, 0xb9, 0x33, 0x53, 0x1b, 0x88, 0x44, 0x4e, 0x60, 0x88, 0x5d, 0x57,
	0x9e, 0xed, 0xaa, 0xfb, 0x1e, 0xad, 0x68, 0xdb, 0x63, 0x9c, 0xec, 0xeb, 0x5c, 0x2d, 0xf3, 0xb9,
	0xfe, 0x51, 0xe5, 0xef, 0xd5, 0xfb, 0x44, 0x42, 0xc9, 0xdf, 0x76, 0x0d, 0xee, 0x83, 0xf2, 0x40,
	0x4e, 0x81, 0x60, 0x66, 0xff, 0x47, 0xfd, 0xf0, 0x3d, 0x2e, 0xca, 0x0a, 0xf8, 0x16, 0xb6, 0x23,
	0xa6, 0x34, 0xb9, 0x9a, 0x52, 0x67, 0xa5, 0x6e, 0x95, 0xc7, 0x92, 0x4c, 0x2c, 0x2a, 0xd9, 0x39,
	0xe4, 0x0f, 0xb0, 0x17, 0x65, 0xd3, 0xc9, 0x2a, 0x46, 0x52, 0x4d, 0x0f, 0xf7, 0x1f, 0xe0, 0x56,
	0xc7, 0xd9, 0xa4, 0x41, 0x77, 0xa2, 0xaa, 0xcf, 0x59, 0xa1, 0x8b, 0x9f, 0x81, 0x21, 0x47, 0xc2,
	0x09, 0xaa, 0x04, 0x36, 0x92, 0x56, 0x69, 0xa4, 0xac, 0xad, 0x52, 0xf3, 0x0f, 0x0d, 0x3a, 0x27,
	0x89, 0xeb, 0xb2, 0xb8, 0x3a, 0xf1, 0xb4, 0xda, 0xc4, 0x5b, 0x07, 0x5d, 0x14, 0x62, 0x29, 0x70,
	0xaa, 0x89, 0x42, 0x2c, 0x45, 0xaa, 0xbe, 0xd1, 0xaa, 0x7c, 0xa3, 0x5d, 0x9d, 0x88, 0x9d, 0xda,
	0x44, 0xec, 0x16, 0x13, 0x51, 0xb6, 0xa2, 0xfc, 0x67, 0x85, 0x5d, 0xa7, 0x53, 0x65, 0x7c, 0x3e,
	0x06, 0xe3, 0x94, 0x47, 0x6c, 0x81, 0xda, 0xdd, 0x01, 0xfd, 0xdd, 0x6c, 0xd8, 0x20, 0x3d, 0x68,
	0x9d, 0xbe, 0xb9, 0x3a, 0x1f, 0x6a, 0x72, 0xf5, 0xfa, 0xc5, 0xf7, 0x97, 0x43, 0x9d, 0x18, 0xd0,
	0xa6, 0x67, 0x2f, 0x27, 0x97, 0xc3, 0xe6, 0xbc, 0x83, 0x8f, 0xf6, 0xf5, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc8, 0x44, 0x90, 0xe7, 0x48, 0x0a, 0x00, 0x00,
}
